import { ThemeProvider } from '@/components/theme-provider'
import { Bio } from '@/utils/data'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `${Bio.name} - Full Stack Developer | Freelance MERN Developer`,
  description: Bio.description,
  keywords: [
    'Rushi portfolio', 'freelance developer India', 'MERN stack developer', 'React developer Latur', 'Node.js expert',
    'WhatsApp automation', 'Next.js developer', 'MongoDB developer', 'restaurant website developer',
    'academy attendance system', 'custom LMS developer', 'freelance software developer', 'React Native developer',
    // ⬇️ Add more specific long-tail keywords below
    'create food order app for restaurant', 'education app developer', 'student attendance system India',
    'WhatsApp Cloud API integration', 'freelance business website', 'responsive web developer',
    'hire MERN developer India', 'business website Latur', 'full stack projects India',
    // (💡 You can expand this to 1000 by generating via script if needed. This covers long-tails for now.)
    'custom ecommerce website developer India', 'hire React Native freelancer Latur',
    'Node.js backend developer India',
    'freelance Next.js portfolio India',
    'restaurant POS system developer',
    'Latur freelance software engineer',
    'MERN stack ecommerce app developer',
    'MongoDB performance optimization expert',
    'create LMS with MERN stack',
    'education portal developer India',
    'build WhatsApp chatbot India',
    'custom CRM developer freelance',
    'React Native mobile app freelancer',
    'food delivery app developer India',
    'freelancer for school ERP system',
    'freelance dashboard developer React',
    'MERN developer for startups India',
    'Next.js SEO expert India',
    'hire freelance mobile developer Latur',
    'create digital menu for restaurant',
    'React frontend developer India',
    'WhatsApp API chatbot developer',
    'Node.js developer for APIs',
    'custom ERP developer India',
    'freelance LMS with video support',
    'developer for tuition app India',
    'real-time chat app MERN stack',
    'hire full stack engineer India',
    'restaurant table booking system dev',
    'React developer for admin panels',
    'MERN stack blog developer',
    'Node.js API integration expert',
    'freelancer for Stripe payment gateway',
    'mobile app for food ordering Latur',
    'school attendance app developer India',
    'Next.js portfolio website developer',
    'React Native freelancer for startups',
    'hire remote MERN stack developer',
    'developer for event booking website',
    'freelancer for WhatsApp automation tools',
    'Next.js developer with MongoDB',
    'React Native app with Firebase',
    'education platform with video call dev',
    'MERN developer for custom CMS',
    'build fitness app with React Native',
    'Node.js microservices developer India',
    'React dashboard UI developer',
    'freelance developer school website',
    'freelance developer for coaching class app',
    'React Native expert for iOS Android',
    'ecommerce developer with MERN',
    'developer for logistics dashboard',
    'school fees management system developer',
    'WhatsApp Cloud API freelancer India',
    'Next.js UI/UX web app freelancer',
    'developer for edtech platform India',
    'developer for WhatsApp based alerts',
    'React freelance developer Maharashtra',
    'Node.js cloud functions developer',
    'food order tracking app developer',
    'Latur developer portfolio freelance',
    'React Native expert for delivery app',
    'MERN stack admin dashboard freelancer',
    'hire education app developer India',
    'freelance project tracking tool developer',
    'build online ordering system India',
    'full stack developer with MongoDB',
    'React developer for responsive UI',
    'Node.js backend with Firebase developer',
    'freelancer for custom restaurant software',
    'freelancer for web based LMS India',
    'React Native expert with Push Notifications',
    'Next.js developer for SSR websites',
    'Node.js API with MongoDB expert',
    'freelancer for e-learning app India',
    'React Native education app developer',
    'freelancer for coaching website India',
    'MERN stack freelance services India',
    'Next.js blog and portfolio developer',
    'build PWA with React India',
    'WhatsApp reminder system developer',
    'Node.js freelancer for small business',
    'developer for local business websites',
    'education portal with attendance tracker',
    'custom school app with MERN',
    'build food ordering web app Latur',
    'freelancer for grocery delivery app',
    'React Native expert India remote',
    'Next.js real estate website developer',
    'freelancer for restaurant CRM',
    'developer for appointment booking system',
    'Latur based freelance coder',
    'Node.js + MongoDB expert freelance',
    'React Native developer for marketplace app',
    'freelancer for online course app India',
    'MERN freelancer for admin panel design',
    'school app developer with WhatsApp alerts',
    'restaurant kiosk app developer India',
    'custom chatbot developer India',
    'Next.js ecommerce site with MongoDB',
    'React Native onboarding app freelancer',
    'Node.js developer for scalable apps',
    'website developer Latur',
    'freelance web designer Latur',
    'mobile app developer Latur',
    'React developer Latur Maharashtra',
    'Node.js developer Latur',
    'MERN stack expert Latur',
    'Latur software developer portfolio',
    'Next.js developer in Latur',
    'Latur freelance React Native developer',
    'ecommerce website developer Latur',
    'custom website designer Latur',
    'hire web developer Latur',
    'business website Latur developer',
    'Latur education app developer',
    'freelancer for school websites in Latur',
    'restaurant website designer Latur',
    'best website developer in Latur',
    'Latur website redesign freelancer',
    'mobile responsive site Latur',
    'freelancer for coaching website Latur',
    'freelance LMS developer Latur',
    'Latur tuition class website developer',
    'freelance software engineer Latur',
    'digital portfolio developer Latur',
    'React Native freelancer Latur',
    'Node.js expert in Latur',
    'custom ERP developer Latur',
    'school attendance system Latur',
    'restaurant food order app Latur',
    'WhatsApp automation expert Latur',
    'freelance dashboard developer Latur',
    'developer for local businesses Latur',
    'custom CRM developer Latur',
    'ecommerce app freelancer Latur',
    'freelancer for NGO website Latur',
    'college website developer Latur',
    'institute website designer Latur',
    'hire MERN stack developer Latur',
    'WhatsApp Cloud API Latur expert',
    'mobile website developer Latur',
    'full stack freelance developer Latur',
    'online booking system Latur developer',
    'freelancer for real estate site Latur',
    'PWA developer in Latur',
    'food delivery app developer Latur',
    'freelance React expert Latur',
    'custom CMS developer Latur',
    'freelancer for Latur startups',
    'online portfolio developer Latur',
    'developer for digital business card Latur',
    'freelancer for logistics website Latur',
    'freelancer for medical website Latur',
    'education LMS website Latur',
    'Next.js SEO expert Latur',
    'React + Firebase developer Latur',
    'developer for hotel website Latur',
    'freelance Shopify developer Latur',
    'ecommerce integration developer Latur',
    'WordPress to MERN migration Latur',
    'Latur coaching class app developer',
    'freelance food ordering site Latur',
    'Node API freelancer Latur',
    'WhatsApp notification system Latur',
    'custom backend developer Latur',
    'freelancer for local ERP Latur',
    'hospital website developer Latur',
    'freelancer for wedding website Latur',
    'online form developer Latur',
    'Latur alumni portal developer',
    'freelance Android app Latur',
    'iOS app developer Latur',
    'payment gateway integration Latur',
    'freelancer for resume builder Latur',
    'job portal developer Latur',
    'digital attendance system Latur',
    'freelancer for exam portal Latur',
    'developer for grocery app Latur',
    'Latur freelancer for delivery app',
    'whatsapp chatbot developer Latur',
    'UI/UX designer freelancer Latur',
    'student portal developer Latur',
    'freelancer for shopping cart site Latur',
    'freelancer for billing software Latur',
    'Latur web maintenance freelancer',
    'real-time app developer Latur',
    'freelance React admin dashboard Latur',
    'Next.js SaaS website developer Latur',
    'custom analytics dashboard Latur',
    'freelancer for inventory app Latur',
    'school app developer in Latur',
    'developer for event site Latur',
    'freelancer for portfolio site Latur',
    'travel booking app developer Latur',
    'freelancer for spa website Latur',
    'Latur web hosting and developer',
    'freelancer for domain + website Latur',
    'WhatsApp cloud API dev Latur',
    'custom landing page Latur developer',
    'Latur based freelance coder',
    'hire full stack freelancer Latur',
    'web consultant Latur',
    'digital business setup Latur developer',
    'website banwane wala Latur',
    'mobile app banane wala',
    'school ki website banwana hai',
    'restaurant ka website banana hai',
    'website developer Marathi bolnara',
    'mobile app banana hai business ke liye',
    'whatsapp automation karwana hai',
    'attendance system chahiye school ke liye',
    'apna dukan ka website banana hai',
    'tuition class ka website developer',
    'react developer jo Hindi bolta ho',
    'mera business ka app banana hai',
    'education app banane wala Latur',
    'whatsapp se message bhejne wala system',
    'local website developer near me',
    'mera kirana dukan ka website chahiye',
    'freelancer jo Marathi samjhta hai',
    'coaching institute ka app banana hai',
    'online order lene wala system banana hai',
    'school ke liye app banwana hai',
    'marathi madhe website banavnyacha developer',
    'karyalayacha website banavnyacha developer',
    'khud ka business website banwana hai',
    'mobile se kaam karne wala developer',
    'hindi me samjhane wala app developer',
    'mera hotel ka website chahiye',
    'student ke attendance ke liye app chahiye',
    'restaurant ka food order app banana hai',
    'whatsapp se order lene wala system chahiye',
    'ghar baithke website banwane wala developer',
    'apna vyavsay online karna hai',
    'vyavsayacha website banavnyacha freelancer',
    'school management system banana hai',
    'coaching ka online class app chahiye',
    'video course ka app banana hai',
    'freelancer jo hindi me bat karta ho',
    'apni dukaan online lana hai',
    'small business ke liye app developer',
    'local app developer in Latur',
    'mobile se website banwane wala',
    'vyavsay chalvanyasathi website havay',
    'lokal web developer jo call uthata hai',
    'school ka result system banana hai',
    'marathi madhe software banavnyacha developer',
    'ghar se kaam karne wala developer',
    'whatsapp se appointment lene wala system',
    'doctor ka appointment app banana hai',
    'dental clinic website developer',
    'vyavsayacha whatsapp automation karaycha aahe',
    'kirana store ka app chahiye',
    'ghar baithe software banwane wala',
    'Hindi samajhne wala developer chahiye',
    'school ka digital attendance system chahiye',
    'tuition ke liye LMS banana hai',
    'apna vyapar online lana hai',
    'vyavsay sathi ecommerce site banavnyacha developer',
    'business card jaisa website chahiye',
    'hotel ka online booking system chahiye',
    'wedding hall ka website banana hai',
    'marriage booking website banana hai',
    'apni shop ka mobile app chahiye',
    'bharatiya language samajhne wala coder',
    'app banane wala number chahiye',
    'best app developer Latur Marathi',
    'vyavsayacha android app banavnyacha developer',
    'simple website banwana hai',
    'school ka homework app banana hai',
    'Latur me freelancer developer kaun hai',
    'business whatsapp chatbot chahiye',
    'local vyavsay sathi developer',
    'whatsapp pe fees reminder bhejne wala system',
    'marathi coaching sathi website chahiye',
    'student registration form banwana hai',
    'exam ke result dikhane wala app chahiye',
    'doctor appointment app in Marathi',
    'vyavsay ka order form banwana hai',
    'mobile app banana hai tuition ke liye',
    'local freelancer developer ka number chahiye',
    'online teaching website banwana hai',
    'WhatsApp broadcast karne ka system chahiye',
    'school ka website Latur me banwana hai',
    'bachaon ka attendance app chahiye',
    'vyavsay chalvnyacha online upay',
    'ghar baithe software banane wala banda',
    'vyavsay ka mobile se control system',
    'latur me hindi bolne wala coder',
    'school parent login website chahiye',
    'sasti website banane wala chahiye',
    'Marathi medium school sathi website',
    'vyavsay sathi app banvnar developer',
    'school events dikhane wala app',
    'pustak selling app banana hai',
    'vyavsay karayla digital upay',
    'easy software for local business',
    'online fee collection system chahiye',
    'vyavsay ka database banwana hai',
    'coach ke liye attendance app',
    'college website banana hai Latur',
    'clinic ka online appointment website',
    'vyavsay chalu karanyasathi app chahiye',
    'vyavsay chalu karnyasathi guide developer',
    'Vyapariyon ke liye website banana wala',
    'kirana shop ke liye online dukan app',
    'ghar se kaam karne wale app developer',
    'vyavsayacha digital marketing website',
    'mobile se vyapar ka control chahiye',
    'Latur me sasta developer chahiye',
    'Marathi vyavsay sathi WhatsApp bot',
    'coaching institute ka enquiry system',
    'vyavsay ke liye ready made software',
    'school ka digital notice board app',
    'vyavsay ka invoice software chahiye',
    'vyavsay sathi Marathi software',
    'local dukandar ke liye app',
    'vyavsay chalu karne wala app',
    'vyavsay ka roz ka hisab rakhne wala app',
    'vyavsay ke liye pdf bill banane wala',
    'vyavsay ka digital visiting card',
    'chhoti dukan ke liye website chahiye',
    'coaching batch wise attendance app',
    'digital vyavsay banana hai',
    'mobile pe order lena hai',
    'WhatsApp status se enquiry lena hai',
    'vyavsay registration ka form app',
    'shikshan sanstha ka website developer',
    'college ka admission form app',
    'hostel management app banana hai',
    'student ke marksheet dikhane wala website',
    'education ka app chahiye Marathi me',
    'vyavsay sathi Marathi app',
    'apna vyavsay ka whatsapp bot chahiye',
    'vyavsay sathi mobile receipt app',
    'vyavsay ke liye khud ka CRM',
    'vyavsay ka billing software Hindi me',
    'vyavsay chalane ke liye software',
    'vyavsay ko online kaise kare',
    'mobile se bill banane wala app',
    'vyavsay ke record rakhne wala app',
    'vyavsay marketing ke liye website',
    'ghar baithe kaam dene wala developer',
    'whatsapp se automatic message bhejne wala'

  ],
  authors: [{ name: Bio.name, url: 'https://omkarchebale.vercel.app/' }],
  creator: Bio.name,
  publisher: Bio.name,
  metadataBase: new URL('https://omkarchebale.vercel.app/'),
  openGraph: {
    title: `${Bio.name} - Freelance Full Stack Developer`,
    description: Bio.description,
    url: '',
    siteName: `${Bio.name} Portfolio`,
    locale: 'en_IN',
    type: 'website',
    images: [
      {
        url: 'https://omkarchebale.vercel.app/profile.jpg',
        width: 1200,
        height: 630,
        alt: `${Bio.name} Portfolio`,
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: `${Bio.name} - Freelance Developer`,
    description: Bio.description,
    images: ['https://omkarchebale.vercel.app/profile.jpg'],
    creator: '@chebalerushi',
  },
  alternates: {
    canonical: 'https://omkarchebale.vercel.app/',
  },
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={ inter.className }>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          { children }
        </ThemeProvider>
      </body>
    </html>
  )
}